# Via: https://github.com/pascalgn/automerge-action

name: Automerge

# Enable while working on this file
on:
    push:
        paths: 
            - "automerge.yaml"

# Enable to automerge the daily data updates
# on:
#     pull_request:
#         types:
#             - labeled
#     check_suite:
#         types:
#             - completed

env:
    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
    automerge:
        runs-on: ubuntu-latest

        steps:
        - name: automerge
          uses: "pascalgn/automerge-action@v0.8.1"
          env:
            MERGE_LABELS: "automerge"

        # Tag the release
        - name: Checkout
          uses: actions/checkout@v2
          with:
              ref: master

        - name: Tag release
          run: |
                git diff --exit-code HEAD ||
                (
                    git config --global user.name ZoneDBot &&
                    git config --global user.email robot@zonedb.org &&
                    make tag-version
                )
