name: build-and-test

on: push
  branches: gh-actions

jobs:
  build:
    runs-on: ubuntu-latest
  container:
    image: domainr/ci:swan
  steps:
  - uses: actions/checkout@v1
  - name: Install dependencies
    run: go get -t -d -v ./...
  - name: Build
    run: go build -v
  test:
    needs: build
    steps:
    - name: Create test-results dir
      run: mkdir -p test-results
    - name: Run tests
      run: go test -v -race -bench
      # run: |
      #     trap "go-junit-report < test-results/go-test.log > test-results/go-test-report.xml" EXIT
      #     go test -v -race -bench . ./... | tee test-results/go-test.log

# TODO from CircleCI config.yml:
# - build -> Report
# - build -> Deploy
# - "update" job
# - workflows section
