name: Update

# FIXME: Delete when the PR is ready
on:
  push:
    paths: 
      - "update.yaml"

# Enable for daily auto-updates
# on:
#     schedule:
#     - cron: '07 8 * * *' # 08:07 UTC is 00:07 PST

env:
  ZONEDBOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Go
        uses: actions/setup-go@v2
      
      - name: Build
        run: go build -v

      - name: Update data
        run: make update
      
      - name: Verify repo is unchanged
        run: git diff --exit-code HEAD

      - name: Create a pull request
        run: |
          git diff --exit-code HEAD ||
          (
            git config --global user.name ZoneDBot &&
            git config --global user.email noreply@github.com &&
            git checkout -b "data/$(date -u '+%Y-%m-%dT%H.%M.%SZ')" &&
            git add . && git commit -m 'Data auto-update' &&
            git push origin -u HEAD &&
            hub pull-request --labels automerge -m "Data auto-update: $(date -u '+%Y-%m-%d')"
          )
